def menu ():
    print("¡Bienvenido a la Calculadora Mágica!")
    print("Por favor elija una opcion: ")
    print("1. Suma")
    print("2. Resta")
    print("3. Multiplicacion")
    print("4. Division")
    print("5. Raiz cuadrada")
    print("6. Potencia")
    print("7. Logaritmo")
    print("8. Exponencial")
    print("9. Km a Millas")
    print("10. Fahrenheit a celsius")
    print("11. Salida")